Resources:
  PredictiveLambdaServiceRole110A3CA1:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: the-predictive-lambda/PredictiveLambda/ServiceRole/Resource
  PredictiveLambda0FFE2BEB:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ImageUri:
          Fn::Join:
            - ""
            - - Ref: AWS::AccountId
              - .dkr.ecr.
              - Ref: AWS::Region
              - "."
              - Ref: AWS::URLSuffix
              - /aws-cdk/assets:a91b16f4c77ffa445833938e81ffc8070a10a66db375450a83a9e6f204abace3
      Role:
        Fn::GetAtt:
          - PredictiveLambdaServiceRole110A3CA1
          - Arn
      MemorySize: 4096
      PackageType: Image
      Timeout: 15
    DependsOn:
      - PredictiveLambdaServiceRole110A3CA1
    Metadata:
      aws:cdk:path: the-predictive-lambda/PredictiveLambda/Resource
  EndpointEEF1FD8F:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: Endpoint
      ProtocolType: HTTP
    Metadata:
      aws:cdk:path: the-predictive-lambda/Endpoint/Resource
  EndpointDefaultRoutethepredictivelambdaEndpointDefaultRoute304B32E3PermissionEB27A226:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - PredictiveLambda0FFE2BEB
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: EndpointEEF1FD8F
            - /*/*
    Metadata:
      aws:cdk:path: the-predictive-lambda/Endpoint/DefaultRoute/thepredictivelambdaEndpointDefaultRoute304B32E3-Permission
  EndpointDefaultRouteDefaultRouteIntegration4584A785:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId:
        Ref: EndpointEEF1FD8F
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::GetAtt:
          - PredictiveLambda0FFE2BEB
          - Arn
      PayloadFormatVersion: "2.0"
    Metadata:
      aws:cdk:path: the-predictive-lambda/Endpoint/DefaultRoute/DefaultRoute-Integration/Resource
  EndpointDefaultRouteB7B22F2B:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: EndpointEEF1FD8F
      RouteKey: $default
      Target:
        Fn::Join:
          - ""
          - - integrations/
            - Ref: EndpointDefaultRouteDefaultRouteIntegration4584A785
    Metadata:
      aws:cdk:path: the-predictive-lambda/Endpoint/DefaultRoute/Resource
  EndpointDefaultStage0AD21F27:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId:
        Ref: EndpointEEF1FD8F
      StageName: $default
      AutoDeploy: true
    Metadata:
      aws:cdk:path: the-predictive-lambda/Endpoint/DefaultStage/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.76.0,@aws-cdk/assets=1.76.0,@aws-cdk/aws-apigatewayv2=1.76.0,@aws-cdk/aws-apigatewayv2-integrations=1.76.0,@aws-cdk/aws-applicationautoscaling=1.76.0,@aws-cdk/aws-autoscaling-common=1.76.0,@aws-cdk/aws-certificatemanager=1.76.0,@aws-cdk/aws-cloudwatch=1.76.0,@aws-cdk/aws-codeguruprofiler=1.76.0,@aws-cdk/aws-ec2=1.76.0,@aws-cdk/aws-ecr=1.76.0,@aws-cdk/aws-ecr-assets=1.76.0,@aws-cdk/aws-efs=1.76.0,@aws-cdk/aws-elasticloadbalancingv2=1.76.0,@aws-cdk/aws-events=1.76.0,@aws-cdk/aws-iam=1.76.0,@aws-cdk/aws-kms=1.76.0,@aws-cdk/aws-lambda=1.76.0,@aws-cdk/aws-logs=1.76.0,@aws-cdk/aws-route53=1.76.0,@aws-cdk/aws-s3=1.76.0,@aws-cdk/aws-s3-assets=1.76.0,@aws-cdk/aws-servicediscovery=1.76.0,@aws-cdk/aws-sqs=1.76.0,@aws-cdk/aws-ssm=1.76.0,@aws-cdk/cloud-assembly-schema=1.76.0,@aws-cdk/core=1.76.0,@aws-cdk/cx-api=1.76.0,@aws-cdk/region-info=1.76.0,jsii-runtime=Python/3.7.2
    Metadata:
      aws:cdk:path: the-predictive-lambda/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Outputs:
  HTTPAPIUrl:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: EndpointEEF1FD8F
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

